name: 'Generate docker image version'
description: 'Generate docker image version'
outputs:
  new-tag:
    description: 'The new docker version'
    value: ${{ steps.generate-new-tag.outputs.new-tag }}
runs:
  using: "composite"
  steps:
    - name: Generate docker image version
      id: generate-new-tag
      run: |
        LATEST_TAG=$(curl -s "https://registry.hub.docker.com/v2/repositories/datnh99/demo-image/tags/?page_size=1" | jq -r '.results[0].name')
        if [[ -z "$LATEST_TAG" ]] ||  [[ "$LATEST_TAG" == "null" ]]; then
          LATEST_TAG="1.0.1"
        fi
        echo "new-tag=$LATEST_TAG" >> $GITHUB_OUTPUT
      shell: bash