name: Update from Upstream

on:
  workflow_dispatch:

jobs:

  update-fork:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/datnh99/demo
          git fetch upstream
          git checkout main
          git merge upstream/main
          git config --global user.email "dat.nguyenhuu.dev@gmail.com"
          git config --global user.name "dat-nguyenhuu"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'chore: Update from upstream'
          title: 'chore: Update from upstream'
          body: 'This PR updates the fork repo with the latest changes from the upstream repo.'
          branch: 'update-from-upstream'
          base: 'main'